kb_def:
  render:
    name: ui
    template: ui_template
    resolvers:
    - {id: ui, type: kb_info}
  resolvers:
  - id: base_fragments
    type: multi-document-retrieval
    files: [general-rules.md]
  rows:
    domain_row:
      primary: '1234567890'
      secondary: '!"#¤%&/()='
    prompt_row:
      primary: qwer
      secondary: QWER
    action_row:
      primary: asdf
      secondary: ASDF

domains:
- name: bootstrap
  plan: {name: bootstrap_plan}
  resolvers:
  - {id: domain_fragments, type: multi-document-retrieval, files: [
        domain-bootstrap.md]}
  renders:
  - name: bootstrap
    template: prompt_template
    resolvers:
    - {id: repo_content, type: repo_content, includes: [bootstrap], excludes: [.clanker, 
          .git], sorting: normal}

- name: py-controller
  plan: {name: controller_plan}
  resolvers:
  - {id: domain_fragments, type: multi-document-retrieval, files: [
        domain-bootstrap.md]}
  renders:
  - name: py-controller
    template: prompt_template
    resolvers:
    - {id: repo_content, type: repo_content, includes: [controller], excludes: [.clanker, 
          .git, controller/compile-and-push.sh, controller/Dockerfile], sorting: normal}

- name: go-controller
  plan: {name: go_controller_plan}
  resolvers:
  - {id: domain_fragments, type: multi-document-retrieval, files: [
        domain-bootstrap.md]}
  renders:
  - name: src
    template: prompt_template
    resolvers:
      - id: repo_content
        type: repo_content
        includes: 
          - bootstrap
          - go-controller/src
          - pm-harness
        excludes: 
          - .clanker
          - .git
          - bootstrap/status.md
        sorting: normal

- name: pm
  plan: {name: proxmox_vm_factory_plan}
  resolvers:
  - {id: domain_fragments, type: multi-document-retrieval, files: [
        domain-bootstrap.md]}
  renders:
  - name: pm-harness
    template: prompt_template
    resolvers:
    - {id: repo_content, type: repo_content, includes: [pm-harness], excludes: [
          .clanker, .git, "pm-harness/vms copy.sh"], sorting: normal}