kb_def:
  render:
    name: ui
    template: ui_template
    resolvers:
    - {id: ui, type: kb_info}
  resolvers:
  - id: base_fragments
    type: multi-document-retrieval
    files: [general-rules.md]
  rows:
    domain_row:
      primary: '1234567890'
      secondary: '!"#¤%&/()='
    prompt_row:
      primary: qwer
      secondary: QWER
    action_row:
      primary: asdf
      secondary: ASDF

domains:
- name: bootstrap
  resolvers:
  - {id: domain_fragments, type: multi-document-retrieval, files: [
        bootstrap.md, bootstrap-backlog.md]}
  renders:
  - name: bootstrap
    resolvers:
    - {id: prompt_fragments, type: multi-document-retrieval, files: []}
    - {id: repo_content, type: repo_content, includes: [bootstrap], sorting: normal}

- name: controller
  resolvers:
  - {id: repo_content, type: repo_content, includes: [go-controller/src], sorting: normal} 
  - {id: domain_fragments, type: multi-document-retrieval, files: [controller.md]}
  renders:
  - name: plan
    resolvers:
    - {id: prompt_fragments, type: multi-document-retrieval, files: [controller-backlog.md, plan-mode.md]}
  - name: execute
    resolvers:
    - {id: prompt_fragments, type: multi-document-retrieval, files: [controller-backlog.md, do-mode.md]}
  - name: doc-mgm
    resolvers:
    - {id: prompt_fragments, type: multi-document-retrieval, files: [controller-backlog.md, doc-mgmnt.md, {"file": "project-history.md", "tail_lines": 8}]}

- name: debloat
  resolvers:
  - {id: repo_content, type: repo_content, includes: [go-controller/src], sorting: normal}
  - {id: domain_fragments, type: multi-document-retrieval, files: [debloat.md]}
  renders:
  - name: compression
    resolvers:
    - {id: prompt_fragments, type: multi-document-retrieval, files: [code-compression.md]}

  - name: decouple
    resolvers:
    - {id: repo_content, type: repo_content, includes: [go-controller/src], excludes: [go-controller/src/infra], sorting: normal}
    - {id: prompt_fragments, type: multi-document-retrieval, files: [decouple-strat.md]}

  - name: logging
    resolvers:
    - {id: prompt_fragments, type: multi-document-retrieval, files: [logging-cleanup.md]}

  - name: error-handling
    resolvers:
    - {id: prompt_fragments, type: multi-document-retrieval, files: [error-streamlining.md]}

- name: pm
  resolvers:
  - {id: domain_fragments, type: multi-document-retrieval, files: [
        pm.md, pm-backlog.md]}
  renders:
  - name: pm-harness
    resolvers:
    - {id: prompt_fragments, type: multi-document-retrieval, files: []}
    - {id: repo_content, type: repo_content, includes: [pm-harness], sorting: normal}