kb_def:
  render:
    name: ui
    template: ui_template
    resolvers:
    - {id: ui, type: kb_info}
  resolvers:
  - id: base_fragments
    type: multi-document-retrieval
    files: [general-rules.md]
  rows:
    domain_row:
      primary: '1234567890'
      secondary: '!"#¤%&/()='
    prompt_row:
      primary: qwer
      secondary: QWER
    action_row:
      primary: asdf
      secondary: ASDF

domains:
- name: bootstrap
  plan: {name: bootstrap_plan}
  resolvers:
  - {id: domain_fragments, type: multi-document-retrieval, files: [
        domain-bootstrap.md, bootstrap-backlog.md]}
  renders:
  - name: bootstrap
    template: prompt_template
    resolvers:
    - {id: repo_content, type: repo_content, includes: [bootstrap], sorting: normal}

- name: controller
  plan: {name: controller_plan}
  resolvers:
  - {id: domain_fragments, type: multi-document-retrieval, files: [controller-backlog.md]}
  - {id: repo_content, type: repo_content, includes: [go-controller/src], sorting: normal}
  renders:
  - name: plan
    template: prompt_template
    resolvers:
    - {id: prompt_fragments, type: multi-document-retrieval, files: [plan-mode.md]}
    #- {id: repo_content, type: repo_content, includes: [go-controller/src], sorting: normal}
  - name: execute
    template: prompt_template
    resolvers:
    - {id: prompt_fragments, type: multi-document-retrieval, files: [do-mode.md]}
    #- {id: repo_content, type: repo_content, includes: [go-controller/src], sorting: normal}

  - name: doc-mgm
    template: prompt_template
    resolvers:
    - {id: prompt_fragments, type: multi-document-retrieval, files: [doc-mgmnt.md, project-history.md]}
    #- {id: repo_content, type: repo_content, includes: [go-controller/src], sorting: normal}

  - name: debloat
    template: prompt_template
    resolvers:
    - {id: prompt_fragments, type: multi-document-retrieval, files: [debloat-instructions.md]}
    #- {id: repo_content, type: repo_content, includes: [go-controller/src], sorting: normal}


- name: pm
  plan: {name: proxmox_vm_factory_plan}
  resolvers:
  - {id: domain_fragments, type: multi-document-retrieval, files: [
        domain-bootstrap.md, pm-backlog.md]}
  renders:
  - name: pm-harness
    template: prompt_template
    resolvers:
    - {id: repo_content, type: repo_content, includes: [pm-harness], sorting: normal}